docs_dir: doc/book
site_dir: doc/html
pages:
    - index.md
    - { 'Migration Guide': [{ Introduction: migration/intro.md }, { 'Removed Functionality': migration/removed.md }] }
site_name: zend-eventmanager
site_description: 'zend-eventmanager: Powerful event bus system for Zend Framework'
repo_url: 'https://github.com/zendframework/zend-eventmanager'
copyright: 'Copyright (c) 2015 <a href="http://www.zend.com/">Zend Technologies USA Inc.</a>'
